stages:
  - build
  - test

variables:
  BUILD_DIR: "src"

build:
  stage: build
  image: mcr.microsoft.com/windows/servercore:ltsc2019
  script:
    - $mingwBin = "C:\ProgramData\mingw64\mingw64\bin"
    - $env:Path = "$mingwBin;$env:Path"
    - cd $env:BUILD_DIR
    - Get-Content -Path Makefile_test
    - '$dir = Get-Location; Write-Host "Current directory: $dir"'
    - Get-ChildItem -Force
    - |
      if (Test-Path "$mingwBin\mingw32-make.exe") {
        & "$mingwBin\mingw32-make.exe" -f Makefile_test main basic_tests
      } else {
        Write-Error "mingw32-make.exe not found"
        exit 1
      }
  artifacts:
    paths:
      - ${BUILD_DIR}/main.exe
      - ${BUILD_DIR}/basic_tests.exe
  tags:
    - windows

test:
  stage: test
  image: mcr.microsoft.com/windows/servercore:ltsc2019
  script:
    - $mingwBin = "C:\ProgramData\mingw64\mingw64\bin"
    - $env:Path = "$mingwBin;$env:Path"
    - cd ${BUILD_DIR}
    - if (Test-Path ".\basic_tests.exe") { echo "Running basic_tests.exe..."; .\basic_tests.exe } else { Write-Error "basic_tests.exe not found"; exit 1 }
  tags:
    - windows