stages:
  - build
  - test

variables:
  BUILD_DIR: "src"

build:
  stage: build
  image: gcc:latest 
  script:
    - echo "Building the project "
    - cd ${BUILD_DIR}
    - make 
    - ls -lah 
  artifacts:
    paths:
      - ${BUILD_DIR}/main.exe

test:
  stage: test
  image: gcc:latest
  script:
    - echo "Running main.exe..."
    - cd ${BUILD_DIR}
    - chmod +x main.exe  
    - ./main.exe  